task_manager/authentication/urls.py
from django.urls import path
from .views import *

app_name = 'auth'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register_page'),
    path('auth/', AuthView.as_view(), name='auth_page'),
    path('logout/', LogoutView.as_view(), name='logout_page'),
    path('vkloginrequest/', VkRequest.as_view(), name='vk_request'),
    path('vkloginresponse/', VkResponse.as_view(), name='vk_response'),
    path('vklogout/', Vk_logout.as_view(), name='vk_logout')
]

task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
import datetime as dt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('task_module.urls')),
    path('', RedirectView.as_view(url=f'/{dt.datetime.now().year}'), name='main_redirect'),
    path('', include('vksdk.urls'))
]

task_manager/vksdk/urls.py
from django.urls import path
from .vk_settings import CALLBACK_URL
from .views import CallBackView
from .admin import admin_site

urlpatterns = [
    path(CALLBACK_URL, CallBackView.as_view(), name='callback_url'),
    path('vk-admin/', admin_site.urls)
]

task_manager/authentication/models.py
import pickle

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import PermissionsMixin


class CustomManager(BaseUserManager):
    def create_user(self, email, password):
        if not email:
            raise ValueError('Please input email address')
        user = MyUser(email=email, password=make_password(password))
        user.save()
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email=email, password=password)
        user.is_staff = True
        return user


class PickleField(models.BinaryField):
    def get_prep_value(self, value):
        return pickle.dumps(value)

    def from_db_value(self, value, expression, connection):
        if value is None:
            return value
        return pickle.loads(value)

    def to_python(self, value):
        if value is None:
            return value
        return pickle.loads(value)

    def value_to_string(self, obj):
        value = self.value_from_object(obj)
        return self.get_prep_value(value).rows


class MyUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=256)
    vk = PickleField(null=True)
    is_staff = models.BooleanField(default=False)

    REQUIRED_FIELDS = ['password']

    USERNAME_FIELD = 'email'

    objects = CustomManager()

    def __str__(self):
        return self.email

    @property
    def is_authenticated(self):
        return True

    @property
    def is_superuser(self):
        return True

    @property
    def is_anonymous(self):
        return False

    def is_admin(self):
        return self.is_staff

    is_admin.boolean = True

task_manager/authentication/forms.py
from django.forms import ModelForm
from .models import MyUser
from django import forms
import logging

logger = logging.getLogger('tm.file')


class RegisterForm(ModelForm):

    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(
        attrs={'class': 'InputField', 'placeholder': 'Повторите пароль...'}))

    class Meta:
        model = MyUser
        fields = [
            'email',
            'password'
        ]

        widgets = {
            'email': forms.TextInput(attrs={'class': 'InputField', 'placeholder': 'Введите Email...'}),
            'password': forms.PasswordInput(attrs={'class': 'InputField', 'placeholder': 'Введите пароль...'})
        }

    def clean(self):
        data = super().clean()
        password = data.get('password')
        password2 = data.get('password2')
        if password and password2:
            if password != password2:
                self.add_error('password', 'Пароли должны совпадать')
                raise forms.ValidationError('Пароли должны совпадать', code='Fields aren\'t equal')


class AuthForm(forms.Form):

    email = forms.EmailField(label='Повторите пароль', widget=forms.EmailInput(
        attrs={'class': 'InputField', 'placeholder': 'Введите Email...'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'InputField', 'placeholder': 'Введите пароль...'}))

task_manager/authentication/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import View
from .forms import RegisterForm, AuthForm
from django.contrib.auth import login, authenticate, logout
from .models import MyUser
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import datetime
import logging
import vksdk.auth_manager as VK

file_logger = logging.getLogger('tm.file')


class RegisterView(View):
    def get(self, request):
        context = {
            'register_form': RegisterForm()
        }
        return render(request, 'authentication/register_page.html', context)

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            MyUser.objects.create_user(email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            login(request, user)
            return redirect(reverse('tm:year_page', args=[datetime.datetime.now().year]))
        else:
            return render(request, 'authentication/register_page.html', {'register_form': form})


class AuthView(View):
    def get(self, request):
        context = {
            'auth_form': AuthForm()
        }
        return render(request, 'authentication/auth_page.html', context)

    def post(self, request):
        form = AuthForm(request.POST)
        if form.is_valid():
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                if user.vk is not None:
                    request.session['vk_credentials'] = user.vk
                return redirect(reverse('tm:year_page', args=[datetime.datetime.now().year]))
            else:
                form.add_error('email', 'Такого пользователя не существует')
                return render(request, 'authentication/auth_page.html', {'auth_form': form})
        else:
            return render(request, 'authentication/auth_page.html', {'auth_form': form})


@method_decorator(login_required, name='dispatch')
class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('auth:auth_page'))


@method_decorator(login_required, name='dispatch')
class VkRequest(View):
    def get(self, request):
        return redirect(VK.Auth.make_url(redirect_uri=request.build_absolute_uri(reverse("auth:vk_response")),
                                         scope_list='email',
                                         display='popup'))


@method_decorator(login_required, name='dispatch')
class VkResponse(View):
    def get(self, request):
        user_credentials = VK.Auth.auth(request.build_absolute_uri(reverse("auth:vk_response")),
                                        code=request.GET.get('code'))
        request.session['vk_credentials'] = user_credentials.session_serialize()
        request.user.vk = request.session['vk_credentials']
        request.user.save()
        request.session.modified = True
        return redirect(reverse('tm:settings_page'))


@method_decorator(login_required, name='dispatch')
class Vk_logout(View):
    def get(self, request):
        request.user.vk_id = None
        del request.session['vk_credentials']
        request.user.save()
        return redirect(reverse('tm:settings_page'))

task_manager/authentication/templates/authentication/auth_page.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Авторизация</title>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	{% load static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Odibee+Sans|Open+Sans+Condensed:300&display=swap" rel="stylesheet">
</head>
<body>	
	<div class="main" style="background-color: #2B2B2B;">
		<div class="container-fluid">
			<div class="row justify-content-center align-items-center" style="height: 100vh;">
				<div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 col-12 align-self-center">
					<div class='block-register'>
						<form action="{% url 'auth:auth_page' %}" method='POST' class='register_form d-flex flex-column align-items-center'>
							{% include 'form_template.html' with form=auth_form %}
							<input class="InputField submit p-0" type="submit" value='Авторизация'>
							<span class="d-block"><a href="#" class='auth-links'>Забыли пароль?</a></span>
							<span class="d-block"><a href="{% url 'auth:register_page' %}" class='auth-links'>Регистрация</a></span>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

task_manager/authentication/templates/authentication/register_page.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Авторизация</title>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	{% load static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Odibee+Sans|Open+Sans+Condensed:300&display=swap" rel="stylesheet">
</head>
<body>	
	<div class="main" style="background-color: #2B2B2B;">
		<div class="container-fluid">
			<div class="row justify-content-center align-items-center" style="height: 100vh;">
				<div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 col-12 align-self-center">
					<div class='block-register'>
						<form action="{% url 'auth:register_page' %}" method='POST' class='register_form d-flex flex-column align-items-center'>
							{% include 'form_template.html' with form=register_form %}
							<input class="InputField submit p-0" type="submit" value='Регистрация'>
							<span class="d-block"><a href="{% url 'auth:auth_page' %}" class='auth-links'>Авторизация</a></span>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>