task_manager/authentication/urls.py
from django.urls import path
from .views import *

app_name = 'auth'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register_page'),
    path('auth/', AuthView.as_view(), name='auth_page'),
    path('logout/', LogoutView.as_view(), name='logout_page'),
    path('vkloginrequest/', VkRequest.as_view(), name='vk_request'),
    path('vkloginresponse/', VkResponse.as_view(), name='vk_response'),
    path('vklogout/', Vk_logout.as_view(), name='vk_logout')
]

task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
import datetime as dt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('task_module.urls')),
    path('', RedirectView.as_view(url=f'/{dt.datetime.now().year}'), name='main_redirect'),
    path('', include('vksdk.urls'))
]

task_manager/task_module/urls.py
from django.urls import path
from .views import *

app_name = 'tm'
urlpatterns = [
    path('<int:year>/', MainView.as_view(), name='year_page'),
    path('day/', DayView.as_view(), name='day_page'),
    path('task/', TaskView.as_view(), name='task_page'),
    path('task/<pk>', TaskView.as_view(), name='task_page'),
    path('settings/', SettingsView.as_view(), name='settings_page'),
    path('reminder/<pk>', ReminderView.as_view(), name='reminder_page'),
    path('vkbot/', BotUtils.as_view(), name='bot_utils'),
    path('vkbot/create_reminder', DaylyReminder.as_view(), name='dayly_reminder_view')
]

task_manager/vksdk/urls.py
from django.urls import path
from .vk_settings import CALLBACK_URL
from .views import CallBackView
from .admin import admin_site

urlpatterns = [
    path(CALLBACK_URL, CallBackView.as_view(), name='callback_url'),
    path('vk-admin/', admin_site.urls)
]

task_manager/templates/form_template.html
{% csrf_token %}
{% for error in form.non_field_error %}
	{{ error }}
{% endfor %}
{% for field in form %}
	{{ field }}
	{{ field.errors }}
{% endfor %}

task_manager/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	{% load static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<script src='{% static "jquery-3.4.1.js" %}'></script>
	<script type='module' src="{% static 'scripts.js' %}"></script>
	<!-- side menu -->
	<script src='{% static "ims_menu.js" %}'></script>
	<link rel="stylesheet" href="{% static 'side_menu.css' %}">
	
	<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Odibee+Sans|Open+Sans+Condensed:300&display=swap" rel="stylesheet">
</head>
<body>	
	<div class="main">
		<div class="container-fluid">
			<div class="row mx-0">
				<div class="ims_side_menu">
			        <div class="main_body">
			        	<div class="ims_header pl-2">
			        		<a href="{% url 'main_redirect' %}" style="font-family: 'Lobster', cursive; font-size: 20px; line-height: 29px;">Task Manager</a>	
			        	</div>
			        	<div class="ims_body pt-3">
			        		<nav>
								<ul class='main_ul'>
									<li><a class='link-side-menu' href="{% url 'main_redirect' %}">Главная страница</a></li>
									<li><a class='link-side-menu' href="{% url 'tm:bot_utils' %}">Возможности бота</a></li>
									<li><a class='link-side-menu' href="{% url 'tm:settings_page' %}">Управление</a></li>
									<li><a class='link-side-menu' href="{% url 'auth:logout_page' %}">Выход</a></li>
								</ul>
							</nav>
				      	</div>
			        </div>
			    </div>
				<div class="ml-4 col main-block">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>
	</div>
</body>

<div class="d-none">
	{% block hidden-forms %}
	<div class="newttaskform">
		<form action="{% url 'tm:day_page' %}" method="POST" class='d-flex flex-column justify-content-center' id='maketaskform'>
			<!-- {% include 'form_template.html' with form=NewTTaskForm %} -->
			<div class="form-row"><div class="col">{{NewTTaskForm.title}}</div></div>
			<div class="form-row"><div class="col">{{NewTTaskForm.text}}</div></div>
			<div class="form-row">
				<div class="col-2">
					{{NewTTaskForm.color}}
				</div>
				<div class="col-5">
					{{NewTTaskForm.time_success}}
				</div>
				<div class="col-5">
					{{NewTTaskForm.time_success2}}
				</div>
			</div>
			{{NewTTaskForm.data}}
			<input type="submit" value="Создать задачу" class='InputField p-0'>
		</form>
	</div>
	{% endblock %}

	<!-- Reminder block -->
	<div class="row text-light" id='create_reminder'>
	    <div class="col">
	        <form method='POST' class="d-flex flex-column p-3" style="height: 100%;width: 100%;">
	        	{%csrf_token%}
	            <label>Кастомное напоминание:</label>
	            <hr style="width: 100%;margin-bottom: 16px; margin-top: 0;">
	            <div class="form-row mb-3">
	            	<div class="col-6">
	            		<label for="rem_date_input">Введите дату:</label>
			            <input id='rem_date_input' name="date" class="InputField" type="date" style="margin: 0px" required="true">
			            <div class="invalid-feedback" id='invalid-date-feedback'>
			            	Нельзя ставить напоминания после задачи.
					    </div>
				    </div>
				    <div class="col-6">
				    	<label for="rem_time_input">Введите время:</label>
	            		<input id='rem_time_input' name='time' class="InputField" type="time" style="margin: 0px;margin-top: 0px;" required="true">
	            		<div class="invalid-feedback" id='invalid-time-feedback'>
	            			Дата должна быть между текущей датой и датой задачи.
					    </div>
	            	</div>
				</div>
	            <input class='InputField submit' type="submit" value='Добавить'>
	            <label class='mt-2'>Стандартные напоминания:</label>
	            <hr style="width: 100%;margin-bottom: 16px; margin-top: 0;">
	            <div class="d-flex flex-grow-0 flex-shrink-0 justify-content-around">
	                <button id='add_reminder_1_hour' class="InputField submit" type="button" style="margin-bottom: 15px;width: 45%;">За 1 час</button>
	                <button id='add_reminder_3_hour' class="InputField submit" type="button" style="margin-bottom: 15px;width: 45%;">За 3 часа</button></div>
	            <div class="d-flex justify-content-around">
	                <button id='add_reminder_1_day' class="InputField submit" type="button" style="margin-bottom: 15px;width: 45%;">За 1 день</button>
	                <button id='add_reminder_3_day' class="InputField submit" type="button" style="margin-bottom: 15px;width: 45%;">За 3 дня</button>
	            </div>
	        </form>
	    </div>
	    <div class="col">
	        <div class="table-responsive table-borderless p-3">
	            <table class="table table-striped table-bordered table-sm">
	                <thead>
	                    <tr>
	                        <th class="text-center text-light" style="width: 40%;">Дата</th>
	                        <th class="text-center text-light" style="width: 40%;">Время</th>
	                    </tr>
	                </thead>
	                <tbody class='text-light' id='reminders_list'>
	                </tbody>
	            </table>
	        </div>
	    </div>
	</div>

</div>
</html>